modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ModdingForBlockheads/DefaultOptions/issues"

[[mods]]
modId="defaultoptions"
version="${file.jarVersion}"
displayName="Default Options"
displayURL="https://blay09.net/mods/defaultoptions"
logoFile="defaultoptions-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
A way for modpacks to ship a default (key) configuration without having to include an options.txt file. Also allows local options from any mod .cfg file.
'''

[[dependencies.defaultoptions]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.defaultoptions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.defaultoptions]]
    modId="balm"
    mandatory=true
    versionRange="[2.1.0,)"
    ordering="NONE"
    side="BOTH"
